### ISSUE TITLE
Change order of browsers in BT

### ISSUE THREAD

**Issue by boxfoot** [aloneguid/bt-browser-extensions#1]
(Since there's no repo for BT itself, I wasn't sure where/how to send this feedback.  LMK if there's a better place to send it)

Is there a way to reorder the browser options in the BT interface?  I would like to manually sort by how much I use each browser and profile.  Currently my least-used profiles are at the top of the list and my most-used at the bottom, so I frequently have to scroll and I wish I didn't.

**Comment by aloneguid** [comment]
this is now available in the latest version

**Comment by boxfoot** [comment]
Amazing, thanks!
